# STAGE 1: Node costruisce i file
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Qui creiamo la cartella /dist con i file pronti
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# STAGE 2: Nginx serve i file
FROM nginx:stable-alpine
# Copiamo i file pronti dallo stage precedente alla cartella di Nginx
COPY --from=build /app/dist /usr/share/nginx/html
# Copiamo la configurazione di Nginx (che scriveremo tra poco)
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]