server {
    listen 80;

    # 1. Serve il Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Inoltra le chiamate API al Backend (Django)
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Gestisce i file statici di Django (Admin, icone, ecc.)
    location /static/django/ {
        alias /app/staticfiles/;
    }
}