server {
    listen 80;

    # Forza l'uso di un DNS pubblico per risolvere l'URL esterno
    resolver 8.8.8.8 valid=30s;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Inoltra le chiamate API al Backend (Django)
    location /api/ {
        # Usa l'URL PUBBLICO del tuo backend qui
        set $backend_url https://backend-service-yk7w.onrender.com;

        proxy_pass $backend_url;
        proxy_set_header Host backend-service-yk7w.onrender.com; # Importante per Django
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Evita che Nginx riscriva i redirect in modo errato
        proxy_redirect off;
    }
}