# Generated by Django 6.0.1 on 2026-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('note', 'Nota Classica'), ('list', 'Checklist'), ('event', 'Evento/Scadenza')], default='note', max_length=30),
        ),
    ]
