# Generated by Django 6.0.2 on 2026-02-24 10:35

import djangoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default=djangoapp.models.get_random_color, max_length=7),
        ),
    ]
